apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: staging-websiteone-frontend
  namespace: staging
  labels:
    app: websiteone-fe
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: websiteone-fe
  template:
    metadata:
      labels:
        app: websiteone-fe
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: "gcr.io/websiteone-frontend/websiteone-frontend:staging-b0c28e5"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30

          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 250m
              memory: 512Mi
