apiVersion: v1
kind: Service
metadata:
  name: staging-esa-frontend
  namespace: staging
  labels:
    app: websiteone-fe-service
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: websiteone-fe
    tier: frontend
